
logging.level:
  org.apache.kafka: INFO
  org.springframework.kafka: TRACE
  com.vmware.tanzulabs.schemaregistry: DEBUG

server:
  port: 8281

spring:

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    properties:
      schema.registry.url: http://localhost:8990
    template:
      default-topic: sensors-2

  cloud:

    schema-registry-client:
      endpoint: http://localhost:8990

    schema:
      avro:
        prefix: vnd
        schema-locations: classpath:avro/sensor.avsc

management:
  endpoints:
    web:
      exposure:
        include: '*'
