
logging.level:
  org.springframework.kafka: DEBUG
  com.vmware.tanzulabs.schemaregistry: DEBUG

server:
  port: 8280

spring:

  application:
    name: spring-kafka-consumer

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    properties:
      schema.registry.url: http://localhost:8990
      group.id: ${spring.application.name}
    template:
      default-topic: sensors

  cloud:

    schema-registry-client:
      endpoint: http://localhost:8990

    schema:
      avro:
        prefix: vnd
        schema-locations: classpath:avro/sensor.avsc

management:
  endpoints:
    web:
      exposure:
        include: '*'
