
logging.level:
  org.springframework.cloud: INFO
  com.vmware.tanzulabs.schemaregistry: DEBUG

server:
  port: 8180

spring:

  application:
    name: scst-consumer

  cloud:

    schema-registry-client:
      endpoint: http://localhost:8990

    schema:
      avro:
        prefix: vnd
        schema-locations: classpath:avro/sensor.avsc

    stream:

      function:
        bindings:
          sensors: sensors-in-0

      bindings:
        sensors-in-0:
          destination: sensors
          group: ${spring.application.name}
          content-type: application/*+avro

management:
  endpoints:
    web:
      exposure:
        include: '*'
